name: Wii U Plugin Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/wiiu-env/wiiupluginsystem:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Plugin
        # We manually export the PATH right before running make
        run: |
          export DEVKITPRO=/opt/devkitpro
          export DEVKITPPC=$DEVKITPRO/devkitPPC
          export PATH=$DEVKITPPC/bin:$PATH
          make clean
          make
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NebulaClient-Plugin
          path: "*.wps"
